{% set version = "1.8.0" %}
{% set sha256 = "58a6f4277ca2bc8565222b3bbd58a177609e9c488e8a72649359ba51450db7d8" %}

package:
  name: gtest
  version: {{ version }}

source:
  fn: release-{{ version }}.tar.gz
  url: https://github.com/google/googletest/archive/release-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  detect_binary_files_with_prefix: False # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake

test:

  commands:
    - test -f ${PREFIX}/lib/libgtest.a                      # [unix]
    - test -f ${PREFIX}/lib/libgtest_main.a                 # [unix]
    - test -d ${PREFIX}/include/gtest                       # [unix]
    - test -f ${PREFIX}/lib/libgtest_dll.so                 # [linux]
    - test -f ${PREFIX}/lib/libgtest_dll.dylib              # [osx]
    - if not exist %LIBRARY_LIB%\gtest.lib exit 1           # [win]
    - if not exist %LIBRARY_LIB%\gtestd.lib exit 1          # [win]
    - if not exist %LIBRARY_LIB%\gtest_main.lib exit 1      # [win]
    - if not exist %LIBRARY_LIB%\gtest_maind.lib exit 1     # [win]
    - if not exist %LIBRARY_BIN%\gtest_dll.dll exit 1       # [win]
    - if not exist %LIBRARY_BIN%\gtest_dlld.dll exit 1      # [win]
    - if not exist %LIBRARY_LIB%\gtest_dll.lib exit 1       # [win]
    - if not exist %LIBRARY_LIB%\gtest_dlld.lib exit 1      # [win]
    - if not exist %LIBRARY_LIB%\gtest-md.lib exit 1        # [win]
    - if not exist %LIBRARY_LIB%\gtest-mdd.lib exit 1       # [win]
    - if not exist %LIBRARY_LIB%\gtest_main-md.lib exit 1   # [win]
    - if not exist %LIBRARY_LIB%\gtest_main-mdd.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\gtest_dll-md.dll exit 1    # [win]
    - if not exist %LIBRARY_BIN%\gtest_dll-mdd.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\gtest_dll-md.lib exit 1    # [win]
    - if not exist %LIBRARY_LIB%\gtest_dll-mdd.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\gtest exit 1               # [win]

about:
  home: https://github.com/google/googletest
  license: BSD 3-Clause
  license_family: BSD
  license_file: googletest/LICENSE
  summary: Google's C++ test framework

extra:
  recipe-maintainers:
    - SylvainCorlay
    - scopatz
